name: Automated tests

on:
  pull_request:
    branches: [ main, master, dev ]

jobs:
  test-api:

    runs-on: ubuntu-latest

    env:
      MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
      MONGO_DATABASE_NAME: ${{ secrets.MONGO_DATABASE_NAME }}

    strategy:
      matrix:
        python-version: [ '3.12' ]

    steps:
    - name: Clone Repository
      uses: actions/checkout@v4

    - name: Python Setup ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Init API in background
      run: |
        uvicorn src.accounts.app:create_app --factory --host 0.0.0.0 --port 8000 &
        
        sleep 5

    - name: Exec Pytest
      run: |
        pytest -v